# 应用配置
application:
  server.port: 7000
  name: register-go

# 日志配置
logrus:
  level: trace
  logFileName: register-go
  filePath: logs/
  #  配置日志切割
  # 30 * 24 * 60 * 60 一个月
  maxAge: 2592000
  # 24 * 60 * 60 一天
  rotationTime: 86400